How the NODE works: {
    shape: sequence_diagram
    Device: IOT Device
    Node: Node
    App: User App

    DB: DB

    Send Live packet: {
        Device->Node: call /l?a each 30sec
        Node->DB: Set data
    }
    Send CMD: { 
        App->Node: call /cmd?address&cmd  send command
        Node<->DB: get ip:port for address
        Node ->Device: call ip:port/cmd?address&cmd  send command
        Device->Node->App: recive command result
    }
  }